name: Publish

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm build:sea

      - name: Zip binary
        run: zip tomo-darwin-arm64.zip tomo

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: tomo-darwin-arm64.zip
